version: '3.4'

services:
  web:
    image: backend
    build: .
    ports:
      - "8000:8000"
    volumes: 
      - ./:/usr/src/backend/
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    depends_on: 
      - db
    environment: 
      - DB_HOST=db
      - DB_PORT=5432
  db:
    image: postgres
    environment:
        - POSTGRES_DB=twitterDEV
        - POSTGRES_USER=twitteradminDEV
        - POSTGRES_PASSWORD=AdminPasswordDEV
    ports: 
      - "5432:5432"
    volumes: 
      - db_data:/var/lib/postgresql/data/
volumes: 
  db_data: