version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  db:
    image: postgres
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres